# Generated by Django 3.2 on 2021-04-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_feedback_product'),
        ('api', '0003_feedback'),
    ]

    operations = [
    ]
